sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.6

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "mimi0j0j@naver.com"
  - git config --global user.name "HWANMIN JEONG"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "Vfd09rjELQO/yM1qSeXH9TctSAGeRNoHczX8wJqkjKnjyyRgvRHomwfzCEIHxHDscLfZcPZwh
             qfs5/4acJt2J1ESwDPlN1YJHP/KLUy/nsRRWRfb1MpQRQOjj3AM80QMSWsEAaBXSjKuowKnIEqWdCxfDK6RZ
             kwP7T3+2xaXySc7tJ84Ar97fyUdd0lVamzOY27VrKsyF4cjZ9zfQkMlMQjNNSHBEt37eX10sDa3sM0Xws0Oe
             aAKLQ+iwKg9FzzFJTcBmlw3D9CpAUUiTetnes23DU3JwwAgNplbPp2ve/CqgCKjQX3uEctga8jX1HA5Ro40m
             +7trGkQR+2E88LzpEgZ5GFLa9GIsyKSduv2kgyia/Lxd8Yhcrv7QN1XeRRCzVuiRG8A/PuVMGCG7IfDqkPq5
             QaLOOMx1uP+1BmorozDp5GbtjiwSB953Pgo8M5b5O+LkdI/OB5NPQFSKVrgif4tf259V9WYYUV7fHPgeNh1E
             1Wx1swg8+icRrs9EPr+5CO9Yo5RHYx9zqOS4aXqnBEM7OXp/SGMBdoMuYSTFG72RsYIVCpuAuYWnMBoEtqec
             MvF314VBJVwR0aXZAPSjGTORLvlyyu57hYCbo2u+mIsYHZ58fBLy1WyTHlNIW/rZMjtrkzeCUPXhzOMBNPpN
             kFdiErQY+d6BPfVF80HzF0="
branches:
  only:
    - master